### ISSUE TITLE
(node:158881) UnhandledPromiseRejectionWarning: SqliteError: no such table: places

### ISSUE THREAD

**Issue by jczhang02** [phiresky/ts-histdbimport#4]
Error appears:
(node:158881) UnhandledPromiseRejectionWarning: SqliteError: no such table: places

Sorry for can't provide more information. 
If u need, please tell me.

**Comment by phiresky** [comment]
you have to have histdb run at least once to initialize the database (i think)

**Comment by jczhang02** [comment]
I have run histdb.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
